-- Run in MySQL: CREATE DATABASE student_db; USE student_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone VARCHAR(20),
  role VARCHAR(50),
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS emp (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  course VARCHAR(100),
  age INT
);

CREATE TABLE IF NOT EXISTS student (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50),
  gender VARCHAR(20),
  mob_no VARCHAR(20),
  dob DATE,
  blood_group VARCHAR(10),
  religion VARCHAR(50),
  class_name VARCHAR(50),
  email VARCHAR(100) NOT NULL,
  section VARCHAR(50),
  fees INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS classname (
  id INT AUTO_INCREMENT PRIMARY KEY,
  className VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS fees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  className VARCHAR(100) NOT NULL,
  fees INT NOT NULL
);

CREATE TABLE IF NOT EXISTS transport (
  id INT AUTO_INCREMENT PRIMARY KEY,
  routeName VARCHAR(100) NOT NULL,
  vehicleNo VARCHAR(50) NOT NULL,
  driverName VARCHAR(100) NOT NULL,
  licenseNo VARCHAR(50),
  phoneNo VARCHAR(20)
);
